# Generated by Django 4.2.9 on 2026-03-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_alter_cohort_options_alter_cohort_unique_together'),
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='cohorts',
            field=models.ManyToManyField(blank=True, help_text='Target one or more cohorts for this survey', related_name='surveys', to='cohorts.cohort'),
        ),
        migrations.AlterField(
            model_name='historicalsurvey',
            name='cohort',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Deprecated — use cohorts (M2M) instead', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cohorts.cohort'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Deprecated — use cohorts (M2M) instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_legacy', to='cohorts.cohort'),
        ),
    ]
