# Generated by Django 4.2.9 on 2026-03-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_site_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['-year', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together=set(),
        ),
    ]
