# Generated by Django 4.2.9 on 2026-03-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_request', 'Session Request'), ('session_confirmed', 'Session Confirmed'), ('session_cancelled', 'Session Cancelled'), ('session_reminder', 'Session Reminder'), ('session_feedback', 'Feedback Requested'), ('message', 'New Message'), ('match', 'New Match'), ('forum_reply', 'Forum Reply'), ('survey', 'New Survey'), ('goal', 'Goal Update'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, help_text='Frontend URL to navigate to', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
