# Generated by Django 4.2.9 on 2026-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session_request', 'Session Request'), ('session_confirmed', 'Session Confirmed'), ('session_cancelled', 'Session Cancelled'), ('session_reminder', 'Session Reminder'), ('session_feedback', 'Feedback Requested'), ('message', 'New Message'), ('match', 'New Match'), ('forum_reply', 'Forum Reply'), ('survey', 'New Survey'), ('goal', 'Goal Update'), ('news_item', 'News Published'), ('system', 'System')], max_length=30),
        ),
    ]
