# Generated by Django 4.2.9 on 2026-07-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_email_pending_emaildigest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCatalogueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(max_length=300)),
                ('recipients', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('debounced', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Catalogue Entry',
                'verbose_name_plural': 'Email Catalogue',
                'ordering': ['name'],
            },
        ),
    ]
