# Generated by Django 4.2.9 on 2026-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_add_post_moderation_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Moderation'), ('visible', 'Visible'), ('flagged', 'Flagged for Review'), ('hidden', 'Hidden')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Moderation'), ('visible', 'Visible'), ('flagged', 'Flagged for Review'), ('hidden', 'Hidden')], default='pending', max_length=20),
        ),
    ]
