# Generated by Django 4.2.9 on 2026-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_alter_historicalpost_status_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='mentor_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='mentor_notified',
            field=models.BooleanField(default=False),
        ),
    ]
