# Generated by Django 4.2.9 on 2026-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_historicalpost_mentor_notified_post_mentor_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='participants_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='participants_notified',
            field=models.BooleanField(default=False),
        ),
    ]
