# Generated by Django 4.2.9 on 2026-07-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_historicalpost_participants_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
