# Generated by Django 4.2.9 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicalmentorwaitinglist_mentorwaitinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmentorprofile',
            name='dbs_certificate_number',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='dbs_certificate_number',
        ),
        migrations.AddField(
            model_name='historicalmentorprofile',
            name='pvg_check_date',
            field=models.DateField(blank=True, help_text='PVG scheme membership date — Scottish users only (no certificate number stored)', null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='engineering_disciplines',
            field=models.JSONField(blank=True, default=list, help_text='All engineering disciplines this user is associated with (up to 3 supported for CRM upload)'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='secondary_roles',
            field=models.JSONField(blank=True, default=list, help_text='Additional roles this user holds (e.g. a Sponsor who is also a Mentor)'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='pvg_check_date',
            field=models.DateField(blank=True, help_text='PVG scheme membership date — Scottish users only (no certificate number stored)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='engineering_disciplines',
            field=models.JSONField(blank=True, default=list, help_text='All engineering disciplines this user is associated with (up to 3 supported for CRM upload)'),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_roles',
            field=models.JSONField(blank=True, default=list, help_text='Additional roles this user holds (e.g. a Sponsor who is also a Mentor)'),
        ),
        migrations.AlterField(
            model_name='historicalmentorprofile',
            name='dbs_check_date',
            field=models.DateField(blank=True, help_text='DBS check completion date (England/Wales)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalscholarprofile',
            name='goals',
            field=models.TextField(blank=True, help_text='What do you hope to achieve through the SPT mentoring programme? Describe your learning objectives, career goals, or skills you want to develop.'),
        ),
        migrations.AlterField(
            model_name='historicalscholarprofile',
            name='scholarship_reference',
            field=models.CharField(blank=True, help_text='SPT internal scholar ID / CRM reference number', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='dbs_check_date',
            field=models.DateField(blank=True, help_text='DBS check completion date (England/Wales)', null=True),
        ),
        migrations.AlterField(
            model_name='scholarprofile',
            name='goals',
            field=models.TextField(blank=True, help_text='What do you hope to achieve through the SPT mentoring programme? Describe your learning objectives, career goals, or skills you want to develop.'),
        ),
        migrations.AlterField(
            model_name='scholarprofile',
            name='scholarship_reference',
            field=models.CharField(blank=True, help_text='SPT internal scholar ID / CRM reference number', max_length=100),
        ),
    ]
