# Generated by Django 4.2.9 on 2026-03-19 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_historicalmentorprofile_dbs_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmentoringmatch',
            name='mentor',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role__in': ['mentor', 'alumni']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalmentorwaitinglist',
            name='preferred_mentor',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role__in': ['mentor', 'alumni']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentoringmatch',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['mentor', 'alumni']}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorwaitinglist',
            name='preferred_mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['mentor', 'alumni']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_scholars', to=settings.AUTH_USER_MODEL),
        ),
    ]
