# Generated by Django 4.2.9 on 2026-03-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_historicalmentoringmatch_mentor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmentoringmatch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mentoring Match', 'verbose_name_plural': 'historical Mentoring Matches'},
        ),
        migrations.AlterModelOptions(
            name='mentoringmatch',
            options={'verbose_name': 'Mentoring Match', 'verbose_name_plural': 'Mentoring Matches'},
        ),
    ]
