# Generated by Django 4.2.9 on 2026-04-09 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fix_mentoringmatch_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscholarprofile',
            name='sponsor',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(('role', 'sponsor'), ('secondary_roles__contains', 'sponsor'), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scholarprofile',
            name='sponsor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'sponsor'), ('secondary_roles__contains', 'sponsor'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_scholars', to=settings.AUTH_USER_MODEL),
        ),
    ]
