# Generated by Django 4.2.9 on 2026-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_site_settings'),
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massmessage',
            name='recipient_programmes',
            field=models.ManyToManyField(blank=True, to='cohorts.programme'),
        ),
    ]
