# Generated by Django 4.2.9 on 2026-03-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_add_replies_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Mentoring'), ('sponsor_update', 'Sponsor Update'), ('mass_message', 'Mass Message')], default='direct', max_length=20),
        ),
    ]
