# Generated by Django 4.2.9 on 2026-04-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_add_mass_message_conversation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='support_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], help_text='Workflow status for support conversations. Null for non-support threads.', max_length=20, null=True),
        ),
    ]
