# Generated by Django 4.2.9 on 2026-06-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_add_conversation_support_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='abusereport',
            name='reported_content',
            field=models.TextField(blank=True, help_text='Snapshot of the reported content (message or forum post body) taken when the report was filed, so it survives later edits/deletion.'),
        ),
        migrations.AddField(
            model_name='historicalabusereport',
            name='reported_content',
            field=models.TextField(blank=True, help_text='Snapshot of the reported content (message or forum post body) taken when the report was filed, so it survives later edits/deletion.'),
        ),
    ]
