# Generated by Django 4.2.9 on 2026-06-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_abusereport_reported_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=10),
        ),
    ]
