# Generated by Django 4.2.9 on 2026-07-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_massmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
