# Generated by Django 4.2.9 on 2026-07-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_historicalmessage_edited_at_message_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='is_broadcast',
            field=models.BooleanField(default=False, help_text='True only for the system-authored broadcast row of a mass message; gates rich-text rendering'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_broadcast',
            field=models.BooleanField(default=False, help_text='True only for the system-authored broadcast row of a mass message; gates rich-text rendering'),
        ),
    ]
