# Generated by Django 4.2.9 on 2026-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=500)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact'), ('SUBSTRING', 'Substring'), ('WILDCARD', 'Wildcard'), ('REGEX', 'Regex'), ('EMAIL_PATTERN', 'Email Pattern'), ('URL_FRAGMENT', 'URL Fragment')], default='SUBSTRING', max_length=20)),
                ('category', models.CharField(choices=[('PROFANITY', 'Profanity'), ('SLUR', 'Slur'), ('SEXUAL', 'Sexual'), ('VIOLENCE', 'Violence'), ('DRUGS_ALCOHOL', 'Drugs / Alcohol'), ('CONTACT_LEAK', 'Contact Leak'), ('SAFEGUARDING', 'Safeguarding'), ('OTHER', 'Other')], default='PROFANITY', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low (soft warn)'), ('MEDIUM', 'Medium (flag for review)'), ('HIGH', 'High (auto-block)'), ('CRITICAL', 'Critical (auto-block + admin alert)')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(db_index=True, default='bulk_import_v1', help_text='bulk_import_v1 = importer; admin = manually added via admin UI', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moderation Term',
                'verbose_name_plural': 'Moderation Terms',
                'ordering': ['term'],
                'unique_together': {('term', 'match_type')},
            },
        ),
    ]
