# Generated by Django 4.2.9 on 2026-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnewsitem',
            name='audience_list',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more audiences. When set, overrides the legacy audience field. E.g. ["scholar", "mentor"] targets scholars and mentors without including sponsors.'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='audience_list',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more audiences. When set, overrides the legacy audience field. E.g. ["scholar", "mentor"] targets scholars and mentors without including sponsors.'),
        ),
        migrations.AlterField(
            model_name='historicalnewsitem',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('scholar', 'Scholars'), ('mentor', 'Mentors'), ('sponsor', 'Sponsors')], default='all', help_text='Legacy single-audience field. Use audience_list for multi-audience targeting.', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('scholar', 'Scholars'), ('mentor', 'Mentors'), ('sponsor', 'Sponsors')], default='all', help_text='Legacy single-audience field. Use audience_list for multi-audience targeting.', max_length=20),
        ),
    ]
