# Generated by Django 4.2.9 on 2026-03-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a top-level folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resources.resourcecategory'),
        ),
    ]
