# Generated by Django 4.2.9 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourcecategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresource',
            name='audience_list',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more audiences. When set, this overrides the legacy audience field. E.g. ["scholar", "mentor"] to target scholars and mentors without including sponsors.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='audience_list',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more audiences. When set, this overrides the legacy audience field. E.g. ["scholar", "mentor"] to target scholars and mentors without including sponsors.'),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('scholar', 'Scholars'), ('mentor', 'Mentors'), ('sponsor', 'Sponsors'), ('admin', 'Admin only')], default='all', help_text='Legacy single-audience field. Use audience_list for multi-audience targeting.', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('scholar', 'Scholars'), ('mentor', 'Mentors'), ('sponsor', 'Sponsors'), ('admin', 'Admin only')], default='all', help_text='Legacy single-audience field. Use audience_list for multi-audience targeting.', max_length=20),
        ),
    ]
