# Generated by Django 4.2.9 on 2026-06-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_historicalresource_audience_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareddocument',
            options={'ordering': ['-shared_at']},
        ),
    ]
